### PR TITLE
Add first version of open data license list #87.

### PR DESCRIPTION
**Pull request by Ludee**

### CODE REVIEW

**Comment by Ludee** [comment]
Info, please do not merge yet. There are some aspects missing:
* Use of self written "terms of use"
* A machine readable list of licenses to check for the review process

**Comment by christian-rli** [comment]
Nice draft! Once you're done, I would read over this again for a few minor expression changes. Only a couple comments:

- `There are already lists of approved open-source licenses` approved by who and for what? 
- `(e.g. OSI. In addition, there are some licenses that cover multiple material / domains (software, data, content)` It would probably make sense to phrase that outside of the brackets and provide some more links 
- `and some that only cover a specific domains` links or it didn't happen :)
- In my opinion the sentences above should go below the explanation of what an open license is.
- The open data licenses are grouped by obligations. I think it would be helpful to add a couple sentences under each heading that explains what that obligation is (i.e. more than just a word in brackets in the heading).

**Comment by christian-rli** [comment]
Good job! This closes a bunch of issues.

**Comment by Ludee** [comment]
Great review of the text. Thanks a lot!

**Pull request merged**
