### PR TITLE
UML auto. generate with eralachemy

### PR DESCRIPTION
**Pull request by jh-RLI**
- Access the OEP
- retrieve a sqlalchemy ORM
- use eralchemy to generate and draw an Entity-Relationship-Model
  - also include PK, FK, relations

### CODE REVIEW

**Comment by jh-RLI** [comment]
Successfully generated ERM: https://github.com/open-modex/oedatamodel/pull/1

**Comment by henhuy** [comment]
Here is how I got ErAlchemy to show relationships with other schema than "public" (see bug https://github.com/Alexis-benoist/eralchemy/pull/70):
```
git clone https://github.com/psipika/eralchemy.git
cd eralchemy
git checkout schema-name-relationship-fix
pip install -e .  # Installs local package via pip
```
Now, you can use eralchemy from command line...

**Comment by Ludee** [comment]
Can you please create a JuPy with a Minimal working example and add it to the OEP-Tutorials?
This is an open task for finishing the project.

**Comment by henhuy** [comment]
> Can you please create a JuPy with a Minimal working example and add it to the OEP-Tutorials?
> This is an open task for finishing the project.

@jh-RLI does your thumbs-up mean you will provide example?

**Comment by jh-RLI** [comment]
@henhuy I wanted to extend the jupyter notebook which I already created here in the PR. I'm just not sure yet if eralchemy works with oedialect and if one can create the ERM without direct database access. 
But yes the thumbs up should say that :)

**Comment by christian-rli** [comment]
> @henhuy I wanted to extend the jupyter notebook which I already created here in the PR. I'm just not sure yet if eralchemy works with oedialect and if one can create the ERM without direct database access.
> But yes the thumbs up should say that :)

At the moment it doesn't matter how the ERM are created. We need ERMs for the scenarios of the project, so if you can @jh-RLI , just plase create those, so we can include them in the final report. High priority at the moment.

**Comment by jh-RLI** [comment]
I just had a chat with @christian-rli. I will finish this in the next week.

**Pull request merged**
